const CatalogActionTypes = {
  FETCH_CATALOG_START: 'FETCH_CATALOG_START',
  FETCH_CATALOG_SUCCESS: 'FETCH_CATALOG_SUCCESS',
  FETCH_CATALOG_FAILURE: 'FETCH_CATALOG_FAILURE'
}

export default CatalogActionTypes
